#=============================================================
#                    Premium Buffer NPC
#=============================================================

# Habilitar el sistema
PremiumBuffer_Enabled = true

# ID del NPC (no cambiar sin actualizar el XML y spawn)
PremiumBuffer_NpcId = 50028

# Cantidad maxima de esquemas por jugador
PremiumBuffer_MaxSchemes = 4

# Nivel de enchant bajo (boton izquierdo)
PremiumBuffer_EnchantLow = 15

# Nivel de enchant alto (boton derecho)
PremiumBuffer_EnchantHigh = 30

#-------------------------------------------------------------
# Costo por aplicar esquema
# Item por defecto: 10639 (Custom Server Coin)
#-------------------------------------------------------------

# ID del item de costo
PremiumBuffer_CostItemId = 10639

# Cantidad de items para aplicar esquema al PERSONAJE
PremiumBuffer_CostCharAmount = 5

# Cantidad de items para aplicar esquema al PET
PremiumBuffer_CostPetAmount = 3
